RegisterNetEvent("hEmote:SyncPtfx")
AddEventHandler("hEmote:SyncPtfx", function(EmoteName, NetEntityId)
	TriggerClientEvent("hEmote:SyncPtfx", -1, EmoteName, NetEntityId)
end)

RegisterServerEvent("ServerEmoteRequest")
AddEventHandler("ServerEmoteRequest", function(target, emotename, etype)
	TriggerClientEvent("ClientEmoteRequestReceive", target, emotename, etype)
end)

RegisterServerEvent("ServerValidEmote") 
AddEventHandler("ServerValidEmote", function(target, requestedemote, otheremote)
	TriggerClientEvent("SyncPlayEmote", source, otheremote, source)
	TriggerClientEvent("SyncPlayEmoteSource", target, requestedemote)
end)